/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Rishabh' at '01/02/16 20:01' with Gradle 2.6
 *
 * @author Rishabh, @date 01/02/16 20:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
